version: "3"

services:
  localcosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: localcosmosdb
    tty: true
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
  localstorage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: localstorage
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./azurite:/data
