openapi: 3.0.1
info:
  title: QuestionGPTPortalAPIs
  description: QuestionGPTPortalでのWebアプリケーションから実行するAPIリファレンスです
  version: "1.0"
servers:
  - url: "{API_URI}/api"
paths:
  /tests:
    get:
      summary: コース・テスト一覧取得API
      description: 各コースに属するテストをすべて取得します
      operationId: get-tests
      parameters:
        - name: X-Access-Token
          in: header
          description: Microsoft ID Platformから発行されたアクセストークン
          required: true
          schema:
            type: string
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      testName:
                        type: string
                      length:
                        type: integer
        "401":
          description: アクセスが拒否されました
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
  /tests/{testId}/questions/{questionNumber}:
    get:
      summary: 問題・選択肢取得API
      description: 指定したテストID・問題番号での問題・選択肢を取得します
      operationId: tests-testid-questions-questionnumber
      parameters:
        - name: testId
          in: path
          description: testId
          required: true
          schema:
            type: string
        - name: questionNumber
          in: path
          description: questionNumber
          required: true
          schema:
            type: integer
        - name: X-Access-Token
          in: header
          description: Microsoft ID Platformから発行されたアクセストークン
          required: true
          schema:
            type: string
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  subjects:
                    type: array
                    items:
                      type: object
                      properties:
                        sentence:
                          type: string
                        isIndicatedImg:
                          type: boolean
                        isEscapedTranslation:
                          type: boolean
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        sentence:
                          type: string
                        img:
                          type: string
                          nullable: true
                        isEscapedTranslation:
                          type: boolean
                  isMultiplied:
                    type: boolean
        "400":
          description: リクエストパラメーターが不正です
          content:
            application/json:
              schema:
                type: string
        "401":
          description: アクセスが拒否されました
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 指定した問題・選択肢が存在しません
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
  /tests/{testId}/answers/{questionNumber}:
    post:
      summary: 回答生成API
      description: 英語の正解の選択肢・正解/不正解の理由を生成します
      operationId: post-answer
      parameters:
        - name: testId
          in: path
          description: testId
          required: true
          schema:
            type: string
        - name: questionNumber
          in: path
          description: questionNumber
          required: true
          schema:
            type: integer
        - name: X-Access-Token
          in: header
          description: Microsoft ID Platformから発行されたアクセストークン
          required: true
          schema:
            type: string
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  correctIdxes:
                    type: array
                    items:
                      type: integer
                      nullable: true
                  explanations:
                    type: array
                    items:
                      type: string
                      nullable: true
                  communityVotes:
                    type: array
                    items:
                      type: string
                      nullable: true
        "400":
          description: リクエストパラメーターが不正です
          content:
            application/json:
              schema:
                type: string
        "401":
          description: アクセスが拒否されました
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 指定した問題・選択肢が存在しません
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
    get:
      summary: 回答取得API
      description: 指定したテストID・問題番号での正解の選択肢・正解/不正解の理由を取得します
      operationId: get-answer
      parameters:
        - name: testId
          in: path
          description: testId
          required: true
          schema:
            type: string
        - name: questionNumber
          in: path
          description: questionNumber
          required: true
          schema:
            type: integer
        - name: X-Access-Token
          in: header
          description: Microsoft ID Platformから発行されたアクセストークン
          required: true
          schema:
            type: string
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  correctIdxes:
                    type: array
                    items:
                      type: integer
                  explanations:
                    type: array
                    items:
                      type: string
                  communityVotes:
                    type: array
                    items:
                      type: string
        "400":
          description: リクエストパラメーターが不正です
          content:
            application/json:
              schema:
                type: string
        "401":
          description: アクセスが拒否されました
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 指定した回答が存在しません
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
  /tests/{testId}/progresses/{questionNumber}:
    post:
      summary: 回答履歴保存API
      description: 指定したテストID・問題番号・ユーザーIDでの回答履歴を保存します
      operationId: post-progress
      parameters:
        - name: testId
          in: path
          description: テストID
          required: true
          schema:
            type: string
        - name: questionNumber
          in: path
          description: 問題番号
          required: true
          schema:
            type: integer
        - name: X-User-Id
          in: header
          description: ユーザーID
          required: true
          schema:
            type: string
      requestBody:
        description: 保存する回答履歴の情報
        content:
          application/json:
            schema:
              type: object
              required:
                - isCorrect
                - choiceSentences
                - choiceImgs
                - selectedIdxes
                - correctIdxes
              properties:
                isCorrect:
                  type: boolean
                  description: 正解の場合はtrue、不正解の場合はfalse
                choiceSentences:
                  type: array
                  description: 選択肢の文
                  items:
                    type: string
                choiceImgs:
                  type: array
                  description: 選択肢の文に続く画像URL(画像がない場合はnull)
                  items:
                    type: string
                    nullable: true
                choiceTranslations:
                  type: array
                  description: 選択肢の文に対応する翻訳文
                  nullable: true
                  items:
                    type: string
                selectedIdxes:
                  type: array
                  description: 選択した選択肢のインデックス
                  items:
                    type: integer
                correctIdxes:
                  type: array
                  description: 正解の選択肢のインデックス
                  items:
                    type: integer
        required: true
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: string
        "400":
          description: リクエストパラメーターが不正です
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
  /en2ja:
    put:
      summary: 翻訳API
      description: 英語の各メッセージを日本語に翻訳します
      operationId: put-en2ja
      parameters:
        - name: X-Access-Token
          in: header
          description: Microsoft ID Platformから発行されたアクセストークン
          required: true
          schema:
            type: string
      requestBody:
        description: 英語の各メッセージ
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: サーバー処理が正常終了しました
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: リクエストパラメーターが不正です
          content:
            application/json:
              schema:
                type: string
        "401":
          description: アクセスが拒否されました
          content:
            application/json:
              schema:
                type: string
        "500":
          description: サーバー処理が異常終了しました
          content:
            application/json:
              schema:
                type: string
