name: Deploy Azure Functions Application

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-functions-app.yaml
      - .github/workflows/reusable-deploy-functions-app.yaml
      - functions**
      - requirements.txt

jobs:
  use-deploy-functions-app-workflow:
    uses: ./.github/workflows/reusable-deploy-functions-app.yaml
    with:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID: ${{ vars.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      FUNCTIONS_NAME: ${{ vars.FUNCTIONS_NAME }}
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}
