name: Run Lint before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "20.10.0"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Bicep
        uses: synergy-au/bicep-lint-action@v1.1
        with:
          analyse-all-files: "true"
