name: Run Lint and Tests before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint Bicep
        uses: synergy-au/bicep-lint-action@v1.1
        with:
          analyse-all-files: "true"

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: pylint functions/**/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with coverage
        run: |
          pushd functions
          coverage run -m unittest discover -s tests
          coverage xml
          popd

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: functions/coverage.xml
          thresholdAll: 0.8
          token: ${{ secrets.GITHUB_TOKEN }}
