name: Run Lint before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Bicep
        uses: synergy-au/bicep-lint-action@v1.1
        with:
          analyse-all-files: "true"

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: pylint functions/**/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with coverage
        run: |
          pushd functions
          coverage run -m unittest discover -s tests
          coverage report --fail-under=80
          popd
